### ISSUE TITLE
Error in docs: failed to execute createElement, the tag name provided is invalid

### ISSUE THREAD

**Issue by G-Rath** [iamhosseindhv/notistack#27]
When exploring the demo, if I have a snack showing with `Use Emojis` checked, the page crashes with the following:

```
main-96a58da2c9b74a445f7b.js:1 DOMException: Failed to execute 'createElement' on 'Document': The tag name provided ('✅') is not a valid name.
    at HTMLDocument.createElement (<anonymous>:1:1554)
    at Wr (https://iamhosseindhv.com/_next/static/commons/main-96a58da2c9b74a445f7b.js:1:172386)
    at Di (https://iamhosseindhv.com/_next/static/commons/main-96a58da2c9b74a445f7b.js:1:202597)
    at da (https://iamhosseindhv.com/_next/static/commons/main-96a58da2c9b74a445f7b.js:1:207899)
    at ha (https://iamhosseindhv.com/_next/static/commons/main-96a58da2c9b74a445f7b.js:1:208771)
    at va (https://iamhosseindhv.com/_next/static/commons/main-96a58da2c9b74a445f7b.js:1:209037)
    at Ya (https://iamhosseindhv.com/_next/static/commons/main-96a58da2c9b74a445f7b.js:1:212585)
    at $a (https://iamhosseindhv.com/_next/static/commons/main-96a58da2c9b74a445f7b.js:1:212097)
    at Ga (https://iamhosseindhv.com/_next/static/commons/main-96a58da2c9b74a445f7b.js:1:211923)
    at ru (https://iamhosseindhv.com/_next/static/commons/main-96a58da2c9b74a445f7b.js:1:217522)
```

I'm running Chrome `70.0.3538.102`.

Standard "this library looks awesome +1" P.S: this library looks awesome!

**Comment by G-Rath** [comment]
@iamhosseindhv no problem - I did think it was probably that, but couldn't find any issue with a stacktrace similar, so figured I'd report it just in case 😄
