### ISSUE TITLE
Not able to test react component using jest

### ISSUE THREAD

**Issue by arunkumar741** [iamhosseindhv/notistack#525]
I am using CRA (create-react-app), jest for testing a component, also using context api

## Expected Behavior

the jest testing need to complete testing

## Current Behavior

whenever i try to mount a component for testing, 
getting error on snackbar on that file
sharing the logs

  ● Test suite failed to run

    TypeError: goober.css is not a function

      4 | import { makeStyles } from "@material-ui/core/styles";
      5 | import Icon from "@material-ui/core/Icon";
    > 6 | import { useSnackbar } from "notistack";
        | ^
      7 | import AppBar from "@mui/material/AppBar";
      8 | import Toolbar from "@mui/material/Toolbar";
      9 | import Typography from "@mui/material/Typography";

      at reduce (node_modules/src/utils/styles.ts:9:20)
          at Array.reduce (<anonymous>)
      at makeStyles (node_modules/src/utils/styles.ts:6:35)
      at Object.<anonymous> (node_modules/src/transitions/Collapse/Collapse.tsx:14:17)
      at Object.<anonymous> (node_modules/notistack/index.js:7:20)
      at Object.user;C:\Arun\Main\smartvision_va\node_modules\notistack\index.js; (src/Testing/Login.test.js:10:11)
      at Object.<anonymous> (src/views/Pages/Login.js:6:1)
      at Object.<anonymous> (src/Testing/Login.test.js:2:1)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        3.594s
## Steps to Reproduce

Link:

1.
2.
3.
4.

## Your Environment

| Tech         | Version |
|--------------|---------|
| Notistack | 3.0.0-alpha.2  |
| React        |     17    |
| Browser      |    windows     |
| etc.         |         |

**Comment by iamhosseindhv** [comment]
Sorry @arunkumar741 - I've gotten to this late - Let me know if you're still experiencing this issue.

**Comment by quanglam2807** [comment]
We're facing the same issue without remedy :(
