### ISSUE TITLE
MUI Transition does not work in 3.0.0-alpha.11

### ISSUE THREAD

**Issue by spjy** [iamhosseindhv/notistack#531]
I recently opened #513 and am attempting to implement this now.

I provided the MUI Grow component into the SnackbarProvider's TransitionComponent prop.

```
<SnackbarProvider
  TransitionComponent={Grow}
></SnackbarProvider>
```

I get these errors whenever a snackbar is enqueued.

```
Uncaught Error: handleEnteredSnack Cannot be called with undefined key
    at SnackbarProvider2._this.handleEnteredSnack (SnackbarProvider.tsx:217:19)
    at chainedFunction (createChainedFunction.ts:19:22)
    at chainedFunction (createChainedFunction.ts:19:22)
    at chainedFunction (createChainedFunction.ts:19:22)
    at chainedFunction (createChainedFunction.ts:18:21)
    at Object.onEntered (Grow.js:73:9)
    at Transition.js:272:24
    at Transition2.nextCallback (Transition.js:334:9)
    at callCallback (react-dom.development.js:13122:12)
    at commitUpdateQueue (react-dom.development.js:13143:9)
SnackbarProvider2._this.handleEnteredSnack @ SnackbarProvider.tsx:217
chainedFunction @ createChainedFunction.ts:19
chainedFunction @ createChainedFunction.ts:19
chainedFunction @ createChainedFunction.ts:19
chainedFunction @ createChainedFunction.ts:18
(anonymous) @ Grow.js:73
(anonymous) @ Transition.js:272
nextCallback @ Transition.js:334
callCallback @ react-dom.development.js:13122
commitUpdateQueue @ react-dom.development.js:13143
commitLayoutEffectOnFiber @ react-dom.development.js:23263
commitLayoutMountEffects_complete @ react-dom.development.js:24578
commitLayoutEffects_begin @ react-dom.development.js:24564
commitLayoutEffects @ react-dom.development.js:24502
commitRootImpl @ react-dom.development.js:26779
commitRoot @ react-dom.development.js:26638
finishConcurrentRender @ react-dom.development.js:25937
performConcurrentWorkOnRoot @ react-dom.development.js:25765
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
12:23:09.620 react_devtools_backend.js:4012 

The above error occurred in the <Transition2> component:
    at Transition2 (http://localhost:4000/node_modules/.vite/deps/chunk-C4U3UZRG.js?v=9c099e95:80:30)
    at Grow2 (http://localhost:4000/node_modules/.vite/deps/chunk-4GUDSMF5.js?v=9c099e95:77:5)
    at http://localhost:4000/node_modules/.vite/deps/chunk-QN4W454T.js?v=9c099e95:495:102
    at div
    at http://localhost:4000/node_modules/.vite/deps/notistack.js?v=9c099e95:865:24
    at div
    at div
    at Transition2 (http://localhost:4000/node_modules/.vite/deps/notistack.js?v=9c099e95:160:30)
    at http://localhost:4000/node_modules/.vite/deps/notistack.js?v=9c099e95:728:24
    at SnackbarItem2 (http://localhost:4000/node_modules/.vite/deps/notistack.js?v=9c099e95:1031:42)
    at div
    at SnackbarContainer2 (http://localhost:4000/node_modules/.vite/deps/notistack.js?v=9c099e95:1162:30)
    at SnackbarProvider2 (http://localhost:4000/node_modules/.vite/deps/notistack.js?v=9c099e95:1202:24)
    at Authenticator (http://localhost:4000/src/features/auth/auth-provider.tsx:55:16)
    at Auth0Provider (http://localhost:4000/node_modules/.vite/deps/@auth0_auth0-react.js?v=9c099e95:3484:23)
    at AuthProvider (http://localhost:4000/src/features/auth/auth-provider.tsx:40:23)
    at Fe (http://localhost:4000/node_modules/.vite/deps/chunk-6VEA444L.js?v=9c099e95:1240:40)
    at InnerThemeProvider (http://localhost:4000/node_modules/.vite/deps/chunk-UZSE3EUV.js?v=9c099e95:5666:17)
    at ThemeProvider (http://localhost:4000/node_modules/.vite/deps/chunk-UZSE3EUV.js?v=9c099e95:5415:5)
    at ThemeProvider2 (http://localhost:4000/node_modules/.vite/deps/chunk-UZSE3EUV.js?v=9c099e95:5674:5)
    at ThemeChangeWrapper (http://localhost:4000/node_modules/.vite/deps/chunk-GPZVOUMB.js?v=9c099e95:51:20)
    at ColorModeProvider (http://localhost:4000/node_modules/.vite/deps/chunk-GPZVOUMB.js?v=9c099e95:24:69)
    at ThemeProvider (http://localhost:4000/node_modules/.vite/deps/chunk-GPZVOUMB.js?v=9c099e95:46:26)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
overrideMethod @ react_devtools_backend.js:4012
logCapturedError @ react-dom.development.js:18572
update.callback @ react-dom.development.js:18605
callCallback @ react-dom.development.js:13122
commitUpdateQueue @ react-dom.development.js:13143
commitLayoutEffectOnFiber @ react-dom.development.js:23290
commitLayoutMountEffects_complete @ react-dom.development.js:24578
commitLayoutEffects_begin @ react-dom.development.js:24564
commitLayoutEffects @ react-dom.development.js:24502
commitRootImpl @ react-dom.development.js:26779
commitRoot @ react-dom.development.js:26638
performSyncWorkOnRoot @ react-dom.development.js:26073
flushSyncCallbacks @ react-dom.development.js:12009
commitRootImpl @ react-dom.development.js:26910
commitRoot @ react-dom.development.js:26638
finishConcurrentRender @ react-dom.development.js:25937
performConcurrentWorkOnRoot @ react-dom.development.js:25765
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
12:23:09.621 react-dom.development.js:12023

Uncaught Error: handleEnteredSnack Cannot be called with undefined key
    at SnackbarProvider2._this.handleEnteredSnack (SnackbarProvider.tsx:217:19)
    at chainedFunction (createChainedFunction.ts:19:22)
    at chainedFunction (createChainedFunction.ts:19:22)
    at chainedFunction (createChainedFunction.ts:19:22)
    at chainedFunction (createChainedFunction.ts:18:21)
    at Object.onEntered (Grow.js:73:9)
    at Transition.js:272:24
    at Transition2.nextCallback (Transition.js:334:9)
    at callCallback (react-dom.development.js:13122:12)
    at commitUpdateQueue (react-dom.development.js:13143:9)
```

**Comment by micktg** [comment]
I had the same problem and used the example from the MUI team:

```js
/**
 * Credit to MUI team @ https://mui.com
 */
import { cloneElement, forwardRef, useRef } from "react";
import { Transition } from "notistack";
import { useForkRef, reflow, getTransitionProps, createTransition } from "components/toast/shared";

//
//
function getScale(value) {
    return `scale(${value}, ${value ** 2})`;
}

//
//
const styles = {
    entering: {
        opacity: 1,
        transform: getScale(1),
    },
    entered: {
        opacity: 1,
        transform: "none",
    },
};

//
//
const Grow = forwardRef((props, ref) => {
    const {
        children,
        in: inProp,
        style,
        timeout = 300,
        onEnter,
        onEntered,
        onExit,
        onExited,
        ...other
    } = props;

    const nodeRef = useRef(null);
    const handleRefIntermediary = useForkRef(children.ref, nodeRef);
    const handleRef = useForkRef(handleRefIntermediary, ref);

    const handleEnter = (node, isAppearing) => {
        reflow(node);

        const { duration, delay, easing } = getTransitionProps({
            style,
            timeout,
            mode: "enter",
        });

        node.style.transition = [
            createTransition("opacity", { duration, delay }),
            createTransition("transform", {
                delay,
                easing,
                duration: duration * 0.666,
            }),
        ].join(",");

        if (onEnter) {
            onEnter(node, isAppearing);
        }
    };

    const handleExit = (node) => {
        const { duration, delay, easing } = getTransitionProps({
            style,
            timeout,
            mode: "exit",
        });

        node.style.transition = [
            createTransition("opacity", { duration, delay }),
            createTransition("transform", {
                easing,
                duration: duration * 0.666,
                delay: delay || duration * 0.333,
            }),
        ].join(",");

        node.style.opacity = "0";
        node.style.transform = getScale(0.75);

        if (onExit) {
            onExit(node);
        }
    };

    return (
        <Transition
            appear
            in={inProp}
            nodeRef={nodeRef}
            onEnter={handleEnter}
            onEntered={onEntered}
            onExit={handleExit}
            onExited={onExited}
            timeout={timeout}
            {...other}
        >
            {(state, childProps) =>
                cloneElement(children, {
                    style: {
                        opacity: 0,
                        transform: getScale(0.75),
                        visibility: state === "exited" && !inProp ? "hidden" : undefined,
                        ...styles[state],
                        ...style,
                        ...children.props.style,
                    },
                    ref: handleRef,
                    ...childProps,
                })
            }
        </Transition>
    );
});

Grow.displayName = "Grow";
export default Grow;
```

```js
const Grow = lazy(() => import("components/toast/Grow")); // import Grow from "components/toast/Grow";

//
//
export const genericSnack = (variant) => {
    const options = {
        preventDuplicate: false,
        variant: variant,
        action: closeAction,
        anchorOrigin: { vertical: "bottom", horizontal: "center" },
        TransitionComponent: Grow,
    };
    return options;
};
```

I hope this helps

**Comment by iamhosseindhv** [comment]
I'm late to this, but for future reader: Here's an example of using `Grow` Transition imported from MUI

https://codesandbox.io/s/inspiring-lamport-kzesxk?file=/App.js
